disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - cyclomatic_complexity
  - identifier_name
  - type_name
  - statement_position
  - no_fallthrough_only
  - closure_parameter_position
  - opening_brace
  - implicit_getter
  - todo
  - switch_case_alignment
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
# included: # paths to include during linting. `--path` is ignored if present.
#   - Source
#excluded: # paths to ignore during linting. Takes precedence over `included`.
#  - Dark
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 120
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
